language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE byob_test;' -U postgres
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: //put in api key 
  app: byob 
  skip_cleanup: true
